{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
{{- $pvcName := printf "%s-data" (include "grr-fyi-chart.fullname" .) }}
{{- $existingPVC := lookup "v1" "PersistentVolumeClaim" .Release.Namespace $pvcName }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $pvcName }}
  labels:
    {{- include "grr-fyi-chart.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if and $existingPVC $existingPVC.spec.volumeName }}
  volumeName: {{ $existingPVC.spec.volumeName }}
  {{- end }}
{{- end }}
