{{- if and (not .Values.existingSecret) (include "grr-fyi-chart.hasSecrets" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grr-fyi-chart.fullname" . }}
  labels:
    {{- include "grr-fyi-chart.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.captcha.secret }}
  ALTCHA_SECRET: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.replication.replicaURL }}
  LITESTREAM_REPLICA_URL: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.replication.accessKeyID }}
  LITESTREAM_ACCESS_KEY_ID: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.replication.secretAccessKey }}
  LITESTREAM_SECRET_ACCESS_KEY: {{ . | b64enc | quote }}
  {{- end }}
{{- end }}
