replicaCount: 1

image:
  repository: registry.hoplon.net/nietaki/grr-fyi
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

logLevel: info
logFormat: text

containerPort: 30666

siteUrl: ""
siteFilePath: priv/site.yml

pprofEnabled: false

persistence:
  enabled: true
  size: 1Gi
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  existingClaim: ""

replication:
  enabled: false
  replicaURL: ""
  accessKeyID: ""
  secretAccessKey: ""

captcha:
  secret: ""
  cost: 5000
  expiryMinutes: 10

existingSecret: ""

serviceAccount:
  create: true
  name: ""
  annotations: {}

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80
  annotations: {}
  loadBalancerClass: ""

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

volumes:
  - name: litestream-meta
    emptyDir: {}

volumeMounts:
  - name: litestream-meta
    mountPath: /litestream-meta

env: []
envFrom: []

nodeSelector: {}
tolerations: []
affinity: {}
